- It's time to learn about first python data analysis library called Numpy
- NumPy (or Numpy) is a linear Algebra Library for Python, the reason it is so important for Data Science with python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main blocks.
- NumPy is alos incredibly fast, as it has bindings to c libraries.
- it is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies(such as Linear Algebra libraries) all sync up with the use of a conda install
- If you have Anaconda, install NumPy by going to your terminal or command and typing:

conda install numpy

pip install numpy

- NumPy arrays are the main way we will use NumPy throughout the course.
- Numpy arrays essentially come in two flavors: vectors and matrices.
- Vectors are strictly 1-d arrays and matrices anr 2-d (but you should note a matrix can still have only one row or one column).

## Let's get started with NumPy arrays!

### NumPy Arrays

In [1]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [2]:
import numpy as np       # importing Numpy Library

In [3]:
# now i can cast that list as an array
np.array(my_list)

array([1, 2, 3])

In [4]:
#if I want to get a two dimensional array or a matrix, I can cast a list of lists.

my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_mat)   #I will get back a two dimensional



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- arrays a lot faster and a lot simpler. Let's go ahead and go through some of the most common ways to do that.



In [6]:
np.arange(0,10)      #passing start and stop

#I'll get an array back from 0 all the way to 9.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
#So if I were all the even numbers from 0 to 10 I could say 0,11.
#And then at a step size of two so that I'd jump in steps of  0 2 4 6 8 10.

np.arange(0,11,2)            #step size = 2

array([ 0,  2,  4,  6,  8, 10])

In [10]:
#if you want to generate arrays of all zeros 
np.zeros(3)                   #single digit in () means 1-d array

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
#if I want a raise of just pure ones I can say that ones.
#And similarly I can pass either a single number or a one dimensional array or a tuple of them mentions

np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# linspace returns evenly spaced numbers over a specified interval.
# it's actually going to take in a third argument of the number of points.
# let's say I have a start of zero and a stop of five and I want to get 10 evenly spaced points between 0 to 5.
# I can pass in a third argument 10 and this returns back a one dimensional vector noted by the one set 
# of brackets here of ten evenly spaced points from zero to five.
# And I can change this third argument to whatever number I want.
# So if I want 100 evenly spaced points from zero to five 
# I can just pass that in and that returns a much larger one dimensional array.

In [15]:
np.linspace(0,5,10) 

#you can tell it's one dimensional by the fact that there's only one bracket here in front of the array.
#when you're dealing with two dimensions you'll see that you have two sets of brackets at opening or closing at the ends.

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
# wecan create an identity matrix using eye.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
 # this is going to create an array of the given shape you pass in and it's going to populate it with.
    np.random.rand(5)

array([0.72841261, 0.59514713, 0.69304249, 0.75892124, 0.40779235])

In [18]:
 np.random.rand(5,5)  #I want a five by five matrix of random numbers.

array([[0.94105146, 0.85528231, 0.16257188, 0.24577484, 0.54001868],
       [0.7721504 , 0.95959601, 0.41910591, 0.88969189, 0.65836268],
       [0.05736257, 0.84350918, 0.9833239 , 0.79427919, 0.65423382],
       [0.30410045, 0.40781453, 0.51842123, 0.37665485, 0.80145878],
       [0.64007039, 0.72613848, 0.77001002, 0.7241961 , 0.20537836]])

In [ ]:
#this will return numbers not from a uniform distribution from 0 to 1 
#but instead from a standard normal distribution center around zero.
#And that means I can go ahead and pass in two and I get two random numbers from a standard normal distribution

In [19]:
#if I want this to be two dimensional I can just pass in two dimensions.

array([-0.74826848,  0.26094645])

In [20]:
np.random.randn(4,4)

array([[-1.07006408,  1.89293532, -1.16138141, -0.57455986],
       [-2.31033182,  0.22436347, -0.71492158, -1.08466315],
       [ 0.32000754, -1.8876452 ,  0.06638873, -0.40403753],
       [ 0.74090419, -0.02365535,  0.40466004, -2.20392481]])

In [21]:
#Rand int and that returns random integers from a low to a high no
np.random.randint(1,100)           
#we'll get the random integer between 1 to 100 the low is iclusive 
#and the high is exclusive meaning one has the chance of selected but 100 is not

80

In [22]:
np.random.randint(1,100,10)   

array([11, 75, 92, 54, 33, 19, 80, 26, 86, 93])

In [ ]:
# I'm going to go ahead and create two new array objects 

In [23]:
arr = np.arange(25)     # array object 1
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr = np.random.randint(0,50,10)    # array object 2
ranarr

array([42, 46, 49, 44, 12,  2, 42, 11, 20, 11])

In [26]:
#One of the most useful methods you can use on an array is the reshape method.
#And that's going to return an array containing the same data if in new shape.


arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
ranarr.max()   #If you want to find the max value in your array.

49

In [29]:
ranarr.min()    #for min element in an array

2

In [30]:
ranarr

array([42, 46, 49, 44, 12,  2, 42, 11, 20, 11])

In [31]:
ranarr.argmax()      #location of max elemnet

2

In [32]:
ranarr.argmin()       #location of min element

5

In [34]:
arr.shape       #because it's a 1-D array

(25,)

In [35]:
#dtype will return the actual data type.


arr.dtype         

dtype('int32')

## NumPy indexing and Selection

In [37]:
import numpy as np

In [39]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr[8]               #at index 8

8

In [41]:
arr[1:5]                 #end is always exclusive

array([1, 2, 3, 4])

In [43]:
arr[0:5]                #taking no from index 0 to index 5

array([0, 1, 2, 3, 4])

In [44]:
 arr[:]               #[:] takes all the values of array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [46]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [48]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [54]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [55]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [56]:
arr_copy = arr.copy()    #this will not make change in an original array.

In [57]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [58]:
arr_copy[:]=100 
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [59]:
arr    

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [76]:
#creating 2-D array
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [61]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [64]:
#if i want to get 5
arr_2d[0][0]           #[first row][first column]

5

In [66]:
arr_2d[0]       #getting first row

array([ 5, 10, 15])

In [67]:
arr_2d[1][1]

25

In [70]:
arr_2d[2][1]

40

In [71]:
# i would recommend using comma in a single bracket 

arr_2d[2,1]

40

In [72]:
#if i want digit 30

arr_2d[1,2]   

30

In [78]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [73]:
arr_2d[:2,1]

array([10, 25])

In [74]:
arr_2d[:2]       # this will result row o and row 1 because end(row2) is exclusive.

array([[ 5, 10, 15],
       [20, 25, 30]])

In [79]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [81]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [84]:
bool_arr = arr>5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [85]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [86]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [87]:
arr[arr<3]

array([1, 2])

In [89]:
arr_d = np.arange(50).reshape(5,10)
arr_d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [90]:
# if i want 13, 14 from second row
arr_d[1,3:5]

array([13, 14])

In [91]:
arr_d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

# Numpy Operations

- array with Array
- Array with Scalars
- universal Array Functions

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

### Array with Scalars

In [7]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [8]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [9]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [10]:
1/0             #however numpy don't give you the error

ZeroDivisionError: division by zero

In [11]:
   arr /arr          #it gives nan when zero divided by zero

<ipython-input-11-47932f420b68>:1: RuntimeWarning: invalid value encountered in true_divide
  arr /arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [12]:
1 / arr

<ipython-input-12-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [14]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

### universal Array Functions

In [15]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [16]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [17]:
np.max(arr)

10

In [18]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [19]:
np.log(arr)

<ipython-input-19-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

# Exercise

#### Import NumPy as NP

In [21]:
import numpy as np

#### create an Array of 10 Zeros

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### create an array of 10 ones

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### create an array of 10 fives

In [24]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [26]:
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of integers from 10 to 50

In [27]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### create an array of all the even integers from 10 to 50

In [29]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### create a 3*3 matrix values ranging from 0 to 8

In [32]:
seq = [1,1,2,3,4,5,6,7,8]
np.array(seq).reshape(3,3)

array([[1, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
# OR

np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3*3 identity matrix

In [39]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### use NumPy to generate a random number between 0 to 1

In [46]:
np.random.rand(1)

array([0.81647915])

#### Use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution

In [49]:
np.random.randn(25)         #1-d array of 25 numbers.

array([ 0.14301975,  0.12387216, -0.73427928,  1.01289036,  0.27667737,
        1.80301102,  0.55578956, -0.4831292 ,  1.4695415 , -1.04414844,
       -0.82723676,  0.75176307, -0.63660595,  1.33175908,  1.20761508,
        0.46986352, -0.8656266 , -1.67399223,  0.22277527,  0.84055045,
       -0.1038245 , -0.54677005,  0.78608062,  1.73157547, -0.64546408])

#### create a 2-D 10*10 matrix having decimal values

In [53]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [58]:
# OR

np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 to 1

In [57]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Numpy indexing and Selection

Now your will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [60]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [61]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN CELL BELOW, OTHERWISE YOU WON'T BE ABLE TO SEE
# THE OUTPUT ANYMORE

In [67]:
# sol:

solution: mat[2:,1:]

In [69]:
# sol:

solution: mat[3,4]

In [ ]:
# sol:

solution : mat[0:3,1:2]

### Get the sum of all the values in mat

In [73]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [74]:
np.sum(mat)       #or mat.sum()

325

### Get the standard deviation of the values in mat

In [75]:
np.std(mat)

7.211102550927978

### Get the sum of all the coumns in mat

In [78]:
mat.sum(axis = 0)

array([55, 60, 65, 70, 75])

# Great Job!